// <auto-generated />
namespace Prog3.RestoDotNet.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tableIdentityOn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tableIdentityOn));
        
        string IMigrationMetadata.Id
        {
            get { return "201906271845281_tableIdentityOn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
